### ISSUE TITLE
Line count bug is still there on staging

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#106] opened 2021-07-28 20:55 UTC
See screenshot.
<img width="1671" alt="Screen Shot 2021-07-29 at 6 52 24 am" src="https://user-images.githubusercontent.com/26546072/127394603-40c011cd-ba84-47dd-a0ec-890ee8049133.png">

**Comment by tomitrescak** [comment] 2022-02-04 00:19
Cannot reproduce this on staging, closing for now.

![image](https://user-images.githubusercontent.com/2682705/152451033-0c6275e4-c748-41bc-956e-89747dc8142a.png)

**Closed as completed by tomitrescak** 2022-02-04 00:19 UTC
