### ISSUE TITLE
Method "must return value" error

### ISSUE THREAD

**Issue by RogerDavidColeman** [tomitrescak/clara-support#127] opened 2022-03-12 23:10 UTC
![Screenshot (5)](https://user-images.githubusercontent.com/100809111/158038151-f4c189e6-0920-48d8-ba96-efb486e194ce.png)
Screenshot 5 show ClaraWorld incorrectly complaining about the method not returning a value.

![Screenshot (7)](https://user-images.githubusercontent.com/100809111/158038174-a1d7a86d-a209-4775-b1b6-eae18def1f2e.png)
Screenshot 7 shows a workaround.

**Comment by tomitrescak** [comment] 2022-03-13 21:26
Roger, thank you for reporting the issue!
This on is not a bug and it is a correct behaviour.

When a function declares to return a value, EVERY branch must return a value.
In your example only one branch under "if treeFront()" return a value, the rest doe not.

I will close this issue. ok?

**Closed as completed by tomitrescak** 2022-03-13 21:26 UTC
