### ISSUE TITLE
Board not visible when editing exercises

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#108] opened 2021-08-03 04:38 UTC
Both staging and prod have this issue. 
I can only experience it on prod, but the student who is in charge of the WACM club also experiences it on staging.

![image](https://user-images.githubusercontent.com/26546072/127958563-f254689b-43f3-4b2c-a258-9ce7ad0b28e5.png)

**Comment by antonwsu** [comment] 2021-08-03 08:04
The student said that the problem happens in Chrome, but not in Edge.

**Comment by antonwsu** [comment] 2021-09-16 09:17
I can confirm that the problem persists. Gilbert also had this issue.

**Comment by tomitrescak** [comment] 2022-02-04 00:16
I will close this for now as I cannot reproduce this, please reopen when there is a reproducible case

**Closed as completed by tomitrescak** 2022-02-04 00:16 UTC
